title: Sail Kokokahi
description: Centralized system for monitoring volunteer hours for Sail Kokokahi
google_analytics:
show_downloads: false
theme: jekyll-theme-midnight
github:
  is_project_page: true
  repository_url: https://github.com/Sail-Kokokahi
gems:
  - jekyll-mentions
